# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/HW0',
                'doc_host': 'https://tyler.github.io',
                'git_url': 'https://github.com/tyler/HW0',
                'lib_path': 'HW0'},
  'syms': {'HW0.core': {'HW0.core.foo': ('core.html#foo', 'HW0/core.py')}}}
