# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/CMPE188HW',
                'doc_host': 'https://Tyler-Dunning.github.io',
                'git_url': 'https://github.com/Tyler-Dunning/CMPE188HW',
                'lib_path': 'CMPE188HW'},
  'syms': {'CMPE188HW.core': {'CMPE188HW.core.foo': ('core.html#foo', 'CMPE188HW/core.py')}}}
